module.exports = {
    "Header":{
        textAlign:'center',
        backgroundColor:'white',
        fontSize:20,
        fontWeight:'bold',
        marginTop:15
    },
    "Box":{
        flex:0.5,
        backgroundColor:'#DAE3D9',
        flexDirection:'column'
    },
    "Text1":{
        color:'black',
        fontSize:20,
        backgroundColor:'#B2B7F6'
    },
    "Text2":{
        color:'black',
        fontSize:20,
        backgroundColor:'#B2F6F0'
    },
    "Text3":{
        color:'black',
        fontSize:20,
        backgroundColor:'#B3EE9A'
    },
    "Text4":{
        color:'black',
        fontSize:20,
        backgroundColor:'#F6F39F'
    },
    "Text5":{
        color:'black',
        fontSize:20,
        backgroundColor:'#F6B09D'
    },
    "Button":{
        width:100,
        height:50,
        backgroundColor:'#4CAF50',
        justifyContent:'center',
    },
    "ButtonText":{
        color:'white',
        fontWeight:'bold',
        fontSize:20,
        textAlign:'center'
    }

}